// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR2PWauB7o3YjrdY1owLB0ssGJmGCZdLo',
    appId: '1:832486590389:web:9abe81c9484b202648fbfc',
    messagingSenderId: '832486590389',
    projectId: 'airbnb-flutter-3405f',
    authDomain: 'airbnb-flutter-3405f.firebaseapp.com',
    storageBucket: 'airbnb-flutter-3405f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQ_fB-wDuZ_WtsHPDQqotRH8iXCdTiPQ',
    appId: '1:832486590389:android:65713e557d395a3948fbfc',
    messagingSenderId: '832486590389',
    projectId: 'airbnb-flutter-3405f',
    storageBucket: 'airbnb-flutter-3405f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWguvSD1-q4tUcXgPdBRfVIpCwpUL2kto',
    appId: '1:832486590389:ios:b885d1c7ce37093548fbfc',
    messagingSenderId: '832486590389',
    projectId: 'airbnb-flutter-3405f',
    storageBucket: 'airbnb-flutter-3405f.firebasestorage.app',
    iosBundleId: 'com.example.bnb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWguvSD1-q4tUcXgPdBRfVIpCwpUL2kto',
    appId: '1:832486590389:ios:b885d1c7ce37093548fbfc',
    messagingSenderId: '832486590389',
    projectId: 'airbnb-flutter-3405f',
    storageBucket: 'airbnb-flutter-3405f.firebasestorage.app',
    iosBundleId: 'com.example.bnb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR2PWauB7o3YjrdY1owLB0ssGJmGCZdLo',
    appId: '1:832486590389:web:b5d4bda9752e6c1e48fbfc',
    messagingSenderId: '832486590389',
    projectId: 'airbnb-flutter-3405f',
    authDomain: 'airbnb-flutter-3405f.firebaseapp.com',
    storageBucket: 'airbnb-flutter-3405f.firebasestorage.app',
  );
}
